### ISSUE TITLE
OSL no longer compatible with multilib OpenEXR

### ISSUE THREAD

**Issue by Tatterdemalian** [AcademySoftwareFoundation/OpenShadingLanguage#1021]
### Problem

OSL build fails with a CMake error when built on a multilib system with OpenEXR version 2.3.0 or higher

**Expected behavior:**  

Successful make and install of OSL 1.8.12 and later.

**Actual behavior:**  

CCMake Error at src/cmake/modules/FindOpenEXR.cmake:66 (string): string sub-command REGEX, mode MATCHALL needs at least 5 arguments total to command. (exact line number of error varies with version, tested with versions listed below)

This appears to be similar to a problem OpenImageIO experienced, due to OpenEXR/OpenEXRConfig.h being changed to a multilib wrapper in OpenEXR 2.3.0, which caused OIIO's FindOpenEXR.cmake to be unable to find the version string it expects.

Build.log (console and error output): https://gist.github.com/Tatterdemalian/232f8f41df14a464b669c5a9236da8d2

### Steps to Reproduce

1. make on a multilib (32 and 64 bit compatible) system with OpenEXR 2.3.0 or later installed.

### Versions

* OSL branch/version: 1.18.12, 1.9.6, 1.9.9, and current head of 'master'
* OS: Gentoo Linux 4.19.37, running multilib setup (x86_64)
* C++ compiler: gcc 8.3.0
* LLVM version: 7.1.0
* OIIO version: 1.8.17

**Comment by lgritz** [comment]
But the one in OIIO is ok now? I will port those same changes to OSL.

**Comment by lgritz** [comment]
Can you try #1022 and see if it helps? That's just a straight port of the current exr-related cmake bits from OIIO.

**Comment by Tatterdemalian** [comment]
Tried it, and sure enough, no more OpenEXR error. Got a completely different build error now, apparently due to LLVM not having its environment variable set properly, but that's probably an issue on my end.

```
CMake Deprecation Warning at CMakeLists.txt:20 (cmake_policy):
  The OLD behavior for policy CMP0046 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LLVM (missing: LLVM_LIBRARIES) (found suitable version
  "7.1.0", minimum required is "5.0")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  src/cmake/modules/FindLLVM.cmake:97 (find_package_handle_standard_args)
  src/cmake/externalpackages.cmake:72 (find_package)
  CMakeLists.txt:143 (include)


make: *** [Makefile:276: cmakesetup] Error 1
```

**Comment by waebbl** [comment]
I encountered the same issue, while trying to prepare a build for version 1.10.5. I was able to solve this another way, by exclusively using pkg-config to request the include file location, as well as the version numbers.

You can get the patch here, if you like:
https://github.com/gentoo/gentoo/pull/12074/commits/bdf72bcbe73834a6256678af1fb2bf3b48419bb1#diff-cc093268d0dda83b886ccc801363c2df

**Comment by lgritz** [comment]
Was this ever resolved to everybody's satisfaction?

**Comment by lgritz** [comment]
Closing because nobody replied to my last comment (over 4 years ago), and since OpenEXR 2.3 is far away in the rearview mirror for us. I assume this is long since fixed.
