### ISSUE TITLE
OSL Mailing list -- Sorry I know this is off-topic but it's not working ?

### ISSUE THREAD

**Issue by SheepDomination** [AcademySoftwareFoundation/OpenShadingLanguage#1358]
What happened to the OSL mailing list ?

**Comment by lgritz** [comment]
https://groups.google.com/g/osl-dev/c/CUXgwRzTz6k

As announced on the old list and still in the archives as the last messages posted, we moved to a new list here: https://lists.aswf.io/g/osl-dev/

**Comment by lgritz** [comment]
Er, or did you mean that the current list is not working? If so, sorry for jumping to conclusions!

**Comment by SheepDomination** [comment]
> Er, or did you mean that the current list is not working? If so, sorry for jumping to conclusions!

The current list isn't working; I subscribed, although when sending a question to the list, it bounces back with an error ?

**Comment by lgritz** [comment]
I just sent a message today and it went through. What error did you get?

**Comment by SheepDomination** [comment]
It is working now, took a few hours.

**Comment by lgritz** [comment]
Great. Maybe a temporary glitch with the list administration.
