### ISSUE TITLE
Packaging Failed with STOP_ON_WARNING=OFF

### ISSUE THREAD

**Issue by MehdiChinoune** [AcademySoftwareFoundation/OpenShadingLanguage#1428]
### Problem

Packaging OSL Failed because it forces "-Werror" on CI environment even with STOP_ON_WARNING=OFF
https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/blob/master/src/cmake/compiler.cmake#L90

**Expected behavior:**  

CI doesn't always mean testing.

**Actual behavior:**  

Many warnings from GCC-11 treated as errors, compilation aborted.

### Steps to Reproduce

- Obvious

### Versions

* OSL branch/version: master
* OS: All
* C++ compiler:  GCC
* LLVM version: 
* OIIO version:

**Comment by MehdiChinoune** [comment]
No reponse, It looks like this project is abandoned!

**Comment by lgritz** [comment]
Not abandoned. But you didn't give much information. 

What errors are you getting? Our CI does test against gcc11, so I'm surprised that you're getting warnings at all.

**Comment by MehdiChinoune** [comment]
> Not abandoned. But you didn't give much information.

You could tell me though!

> What errors are you getting? Our CI does test against gcc11, so I'm surprised that you're getting warnings at all.


I was trying to package OSL 1.11.15.0 for mingw-w64 (https://github.com/msys2/MINGW-packages). I don't remember the warnings as the biggest annoying thing was that I couldn't disable Werror on CI environment.

**Comment by lgritz** [comment]
Apologies; I must have been busy when the issue was filed, and it slipped through the cracks. I wasn't purposely trying to ignore it.

(Note to TSC members and other developers in the OSL community: this isn't all supposed to be on me!)

The "CI" issue is a good point. I will propose a fix to this tomorrow.

**Comment by lgritz** [comment]
Proposed fix: #1446
