### ISSUE TITLE
LLVM 14 incompatibility - TargetRegistry.h has been moved

### ISSUE THREAD

**Issue by StefanBruens** [AcademySoftwareFoundation/OpenShadingLanguage#1496]
https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/blob/a056e181c216b8124048bf1c7a2408bcbef44cf2/src/liboslexec/llvm_util.cpp#L48

https://github.com/llvm/llvm-project/commit/89b57061f7b769e9ea9bf6ed686e284f3e55affe
> Move TargetRegistry.(h|cpp) from Support to MC

**Comment by lgritz** [comment]
Already addressed by https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/pull/1492
But I'm trying to track down why one reference image changes with LLVM14.

**Comment by lgritz** [comment]
Long since fixed
