### ISSUE TITLE
Couldn't build against LLVM 15

### ISSUE THREAD

**Issue by MehdiChinoune** [AcademySoftwareFoundation/OpenShadingLanguage#1587]
### Problem

OSL couldn't be built against LLVM 15

**Expected behavior:**  

To build against LLVM 15

**Actual behavior:**  

https://gist.github.com/MehdiChinoune/e34157d779094c516d5b003901f59d1b

### Steps to Reproduce

1. Install LLVM-15
2. Configure OSL `cmake ..`
3. Build OSL

### Versions

* OSL branch/version: 1.12.6.1-RC1
* OS: Windows 10
* C++ compiler: Clang 15.0.1
* LLVM version: 15.0.1
* OIIO version: 2.3.19.0

**Comment by lgritz** [comment]
I'm already working on this, stay tuned!
