### ISSUE TITLE
icx CI test stopped working

### ISSUE THREAD

**Issue by lgritz** [AcademySoftwareFoundation/OpenShadingLanguage#1590]
In the past couple days, CI tests started failing in the Intel icx compiler test case -- specifically, four batch shading tests now have results that no longer match the reference output.

Here is a failure: https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/actions/runs/3121098041

Here is a success from a couple days earlier AT THE SAME OSL COMMIT, we did no merges in the interim: https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/actions/runs/3103262730

If you look at the log at the top of the "build" section, you can see that what happened in between these tests is that the icx compiler we download (with `yum install -y intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic`) changed from 2022.1.0 to 2022.2.0. It's not a change on the OSL side, something about the new compiler is getting different execution results.

@AlexMWells or @steenax86 do you think you could take a look?

**Comment by steenax86** [comment]
@AlexMWells and I went over this briefly and have a fix. Test failures indicate some change in bit detection/masking behavior. Working on a pull request for this.

**Comment by lgritz** [comment]
I think this is long since fixed but we never closed
