### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by dacorsa** [AcademySoftwareFoundation/OpenShadingLanguage#1614]
Good morning,

i have try to compiling OSL on latest ubuntu 22.10, but i have this error:

[ 16%] Building CXX object src/liboslquery/CMakeFiles/oslquery.dir/oslquery.cpp.o
[ 16%] Building CXX object src/liboslquery/CMakeFiles/oslquery.dir/osolex.cpp.o
[ 16%] Building CXX object src/liboslquery/CMakeFiles/oslquery.dir/__/liboslexec/typespec.cpp.o
/app/OpenShadingLanguage/src/liboslcomp/oslcomp.cpp:24:10: fatal error: clang/Basic/TargetInfo.h: File o directory non esistente
   24 | #include <clang/Basic/TargetInfo.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

what meaning? how solve it?

thanks, best regards.

https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/issues/1614#tasklist-block-136aea27-3b38-456f-89bc-ef4da51bb463

**Comment by dacorsa** [comment]
13:45:13 root@NanoKDE /app/OpenShadingLanguage/build main# dpkg -S TargetInfo.h
ghc: /usr/lib/ghc/Cabal-3.4.1.0/Distribution/Types/TargetInfo.hi
llvm-11-dev: /usr/include/llvm-11/llvm/CodeGen/SelectionDAGTargetInfo.h
llvm-13-dev: /usr/include/llvm-13/llvm/CodeGen/SelectionDAGTargetInfo.h
llvm-15-dev: /usr/include/llvm-15/llvm/CodeGen/SelectionDAGTargetInfo.h
13:47:37 root@NanoKDE /app/OpenShadingLanguage/build main# installa llvm-15-dev
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze... Fatto
Lettura informazioni sullo stato... Fatto   
llvm-15-dev è già alla versione più recente (1:15.0.2-1).

**Comment by lgritz** [comment]
Do you know which version of LLVM you have installed? Which OS distribution are you using?

If you do a fresh build from scratch, can you capture the FULL output of all the status messages that cmake prints to the console and paste them here?

**Comment by dacorsa** [comment]
my distro is Ubuntu 22.10 e i use llvm 15 (as above llvm-15-dev è già alla versione più recente (1:15.0.2-1).)

Clone in 'OpenShadingLanguage' in corso...
remote: Enumerating objects: 40060, done.
remote: Counting objects: 100% (518/518), done.
remote: Compressing objects: 100% (242/242), done.
remote: Total 40060 (delta 322), reused 445 (delta 274), pack-reused 39542
Ricezione degli oggetti: 100% (40060/40060), 184.36 MiB | 26.62 MiB/s, fatto.
Risoluzione dei delta: 100% (28934/28934), fatto.
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze... Fatto
Lettura informazioni sullo stato... Fatto   
llvm è già alla versione più recente (1:15.0-55.1ubuntu1).
pybind11-dev è già alla versione più recente (2.10.0-2).
libpartio-dev è già alla versione più recente (1.14.6-0ubuntu1~22.04.sav0).
0 aggiornati, 0 installati, 0 da rimuovere e 5 non aggiornati.
error: lo specificatore percorso 'default' non corrisponde ad alcun file noto a git
HEAD ora si trova a 1e8ef316 Try to have more optix-only parts hidden behind OSL_USE_OPTIX (#1608)
Già aggiornato.
Già aggiornato.
rm: impossibile rimuovere '../CMakeCache.txt': File o directory non esistente
-- The CXX compiler identification is GNU 12.2.0
-- The C compiler identification is GNU 12.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring OSL 1.13.2.0
-- CMake 3.25.0-rc2
-- CMake system           = Linux-5.19.0-1007-lowlatency
-- CMake system name      = Linux
-- Project source dir     = /app/OpenShadingLanguage
-- Project build dir      = /app/OpenShadingLanguage/build
-- Project install prefix = /app/OpenShadingLanguage/dist
-- Configuration types    = 
-- Build type             = Release
-- Setting Namespace to: OSL_v1_13_2
-- CMAKE_CXX_COMPILER     = /usr/bin/c++
-- CMAKE_CXX_COMPILER_ID  = GNU
-- Building with C++14, downstream minimum C++14
-- Compiling with NO batched SIMD targets, USE_BATCHED is empty
-- clang-format not found.
-- 
-- * Checking for dependencies...
-- *   - Missing a dependency 'Package'?
-- *     Try cmake -DPackage_ROOT=path or set environment var Package_ROOT=path
-- *     For many dependencies, we supply src/build-scripts/build_Package.bash
-- *   - To exclude an optional dependency (even if found),
-- *     -DUSE_Package=OFF or set environment var USE_Package=OFF 
-- 
-- CMAKE_PREFIX_PATH = /app/OpenShadingLanguage/ext/dist
-- Found Boost 107400 
-- Found ZLIB 1.2.11 
-- Found OpenEXR 3.1.5 
-- Found OpenImageIO 2.3.20.0 
-- Found CONFIG for pugixml (>=1.11)
-- Found pugixml 1.12 
-- Found LLVM 15.0.2 
-- Could NOT find partio (missing: partio_DIR)
-- Found partio  
-- Found Python 3.11.0 
-- Found Qt5 5.15.6 
-- Found BISON 3.8.2 
-- Found FLEX 2.6.4 
-- Found pybind11 2.10.0 
-- All docdeep docs = /app/OpenShadingLanguage/build/src/doc/OSLQuery.md.html;/app/OpenShadingLanguage/build/src/doc/docdeep.md.html
-- Configuring done
-- Generating done
-- Build files have been written to: /app/OpenShadingLanguage/build
[  0%] Generating osllex.cpp
[  2%] Generating osolex.cpp
[  2%] Generating osogram.cpp
[  3%] Generating oslgram.cpp
[  3%] Generating testsuite/runtest.py
[  4%] Building CXX object src/liboslnoise/CMakeFiles/oslnoise.dir/gabornoise.cpp.o
[  5%] Building CXX object src/liboslnoise/CMakeFiles/oslnoise.dir/simplexnoise.cpp.o
[  9%] Building CXX object src/testshade/CMakeFiles/testshade_dso.dir/testshade_dso.cpp.o
[  9%] docdeep OSLQuery
[  9%] Building CXX object src/liboslexec/CMakeFiles/dual_test.dir/dual_test.cpp.o
[  9%] docdeep docdeep
[  9%] Built target CopyFiles
/app/OpenShadingLanguage/src/liboslcomp/oslgram.y: attenzione: 1 salta/riduce il conflitto [-Wconflicts-sr]
/app/OpenShadingLanguage/src/liboslcomp/oslgram.y: attenzione: 3 reduce/reduce conflicts [-Wconflicts-rr]
/app/OpenShadingLanguage/src/liboslcomp/oslgram.y: note: rerun with option '-Wcounterexamples' to generate conflict counterexamples
[ 10%] Linking CXX executable ../../bin/testshade_dso
[ 11%] Linking CXX shared library ../../lib/liboslnoise.so
[ 11%] Linking CXX executable ../../bin/dual_test
[ 11%] Built target generated_docs
[ 11%] Building CXX object src/liboslquery/CMakeFiles/oslquery.dir/oslquery.cpp.o
[ 12%] Building CXX object src/liboslquery/CMakeFiles/oslquery.dir/osogram.cpp.o
[ 14%] Building CXX object src/liboslquery/CMakeFiles/oslquery.dir/osolex.cpp.o
[ 14%] Building CXX object src/liboslquery/CMakeFiles/oslquery.dir/__/liboslexec/typespec.cpp.o
[ 14%] Built target testshade_dso
[ 14%] Built target oslnoise
[ 14%] Built target dual_test
[ 14%] Building CXX object src/liboslnoise/CMakeFiles/oslnoise_test.dir/oslnoise_test.cpp.o
[ 15%] Linking CXX executable ../../bin/oslnoise_test
[ 16%] Building CXX object src/liboslcomp/CMakeFiles/oslcomp.dir/ast.cpp.o
[ 18%] Building CXX object src/liboslcomp/CMakeFiles/oslcomp.dir/codegen.cpp.o
[ 18%] Building CXX object src/liboslcomp/CMakeFiles/oslcomp.dir/typecheck.cpp.o
[ 19%] Building CXX object src/liboslcomp/CMakeFiles/oslcomp.dir/oslcomp.cpp.o
[ 20%] Building CXX object src/liboslcomp/CMakeFiles/oslcomp.dir/__/liboslexec/oslexec.cpp.o
[ 22%] Building CXX object src/liboslcomp/CMakeFiles/oslcomp.dir/__/liboslexec/typespec.cpp.o
[ 22%] Building CXX object src/liboslcomp/CMakeFiles/oslcomp.dir/oslgram.cpp.o
[ 22%] Building CXX object src/liboslcomp/CMakeFiles/oslcomp.dir/osllex.cpp.o
[ 22%] Building CXX object src/liboslcomp/CMakeFiles/oslcomp.dir/symtab.cpp.o
[ 22%] Linking CXX shared library ../../lib/liboslquery.so
[ 22%] Built target oslquery
[ 24%] Generating llvm_ops_host_rs.bc
[ 24%] Generating osolex.cpp
[ 26%] Generating llvm_ops_host.bc
[ 26%] Generating opmatrix_host_rs.bc
[ 26%] Generating oslgram.cpp
[ 28%] Generating osllex.cpp
[ 28%] Generating osogram.cpp
[ 28%] Building CXX object src/oslinfo/CMakeFiles/oslinfo.dir/oslinfo.cpp.o
[ 29%] Building CXX object src/liboslquery/CMakeFiles/pyoslquery.dir/py_osl.cpp.o
/app/OpenShadingLanguage/src/liboslexec/../liboslcomp/oslgram.y: attenzione: 1 salta/riduce il conflitto [-Wconflicts-sr]
/app/OpenShadingLanguage/src/liboslexec/../liboslcomp/oslgram.y: attenzione: 3 reduce/reduce conflicts [-Wconflicts-rr]
/app/OpenShadingLanguage/src/liboslexec/../liboslcomp/oslgram.y: note: rerun with option '-Wcounterexamples' to generate conflict counterexamples
[ 30%] Linking CXX executable ../../bin/oslinfo
[ 30%] Linking CXX shared module ../../lib/python/site-packages/oslquery.so
[ 30%] Built target oslinfo
/app/OpenShadingLanguage/src/liboslcomp/oslcomp.cpp:24:10: fatal error: clang/Basic/TargetInfo.h: File o directory non esistente
   24 | #include <clang/Basic/TargetInfo.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [src/liboslcomp/CMakeFiles/oslcomp.dir/build.make:118: src/liboslcomp/CMakeFiles/oslcomp.dir/oslcomp.cpp.o] Errore 1
gmake[1]: *** [CMakeFiles/Makefile2:1113: src/liboslcomp/CMakeFiles/oslcomp.dir/all] Errore 2
gmake[1]: *** Attesa per i processi non terminati....
[ 30%] Built target pyoslquery
[ 30%] Built target oslnoise_test
[ 31%] Generating osl_llvm_compiled_ops.bc
[ 32%] Generating osl_llvm_compiled_ops.bc.cpp

[ 32%] Generating osl_llvm_compiled_rs_dependent_ops.bc
[ 33%] Generating osl_llvm_compiled_rs_dependent_ops.bc.cpp
[ 33%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/shadingsys.cpp.o
[ 35%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/dictionary.cpp.o
[ 36%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/context.cpp.o
[ 36%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/instance.cpp.o
[ 37%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/loadshader.cpp.o
[ 38%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/master.cpp.o
[ 39%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/opcolor.cpp.o
[ 40%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/closure.cpp.o
[ 40%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/opmatrix.cpp.o
[ 40%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/opmessage.cpp.o
[ 42%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/opnoise.cpp.o
[ 42%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/opspline.cpp.o
[ 43%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/optexture.cpp.o
[ 43%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/opstring.cpp.o
[ 44%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/oslexec.cpp.o
[ 45%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/pointcloud.cpp.o
[ 46%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/constfold.cpp.o
[ 46%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/rendservices.cpp.o
[ 48%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/typespec.cpp.o
[ 49%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/lpexp.cpp.o
[ 48%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/runtimeoptimize.cpp.o
[ 50%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/lpeparse.cpp.o
[ 50%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/automata.cpp.o
[ 52%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/opclosure.cpp.o
[ 53%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/shadeimage.cpp.o
[ 53%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/accum.cpp.o
[ 53%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/backendllvm.cpp.o
[ 54%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/llvm_gen.cpp.o
[ 55%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/llvm_instance.cpp.o
[ 56%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/llvm_util.cpp.o
[ 56%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/rs_fallback.cpp.o
[ 57%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/__/liboslcomp/ast.cpp.o
[ 59%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/__/liboslcomp/oslcomp.cpp.o
[ 59%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/__/liboslcomp/codegen.cpp.o
[ 60%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/__/liboslcomp/symtab.cpp.o
[ 60%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/__/liboslcomp/typecheck.cpp.o
[ 61%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/osogram.cpp.o
[ 62%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/osolex.cpp.o
[ 63%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/oslgram.cpp.o
[ 63%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/osllex.cpp.o
[ 64%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/osl_llvm_compiled_ops.bc.cpp.o
[ 65%] Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/osl_llvm_compiled_rs_dependent_ops.bc.cpp.o
/app/OpenShadingLanguage/src/liboslcomp/oslcomp.cpp:24:10: fatal error: clang/Basic/TargetInfo.h: File o directory non esistente
   24 | #include <clang/Basic/TargetInfo.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [src/liboslexec/CMakeFiles/oslexec.dir/build.make:1022: src/liboslexec/CMakeFiles/oslexec.dir/__/liboslcomp/oslcomp.cpp.o] Errore 1
gmake[2]: *** Attesa per i processi non terminati....

gmake[1]: *** [CMakeFiles/Makefile2:1192: src/liboslexec/CMakeFiles/oslexec.dir/all] Errore 2
gmake: *** [Makefile:166: all] Errore 2
20:02:07 root@NanoKDE /app/OpenShadingLanguage/build main#

**Comment by lgritz** [comment]
In addition to the llvm-15-dev package, are you sure you also have the clang-15 package installed?

**Comment by dacorsa** [comment]
YES:

apt install clang-15
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze... Fatto
Lettura informazioni sullo stato... Fatto   
clang-15 è già alla versione più recente (1:15.0.2-1).
0 aggiornati, 0 installati, 0 da rimuovere e 5 non aggiornati.

**Comment by dacorsa** [comment]
apt --installed list |grep clang

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

clang-15/kinetic,now 1:15.0.2-1 amd64 [installato]
clang-format-15/kinetic,now 1:15.0.2-1 amd64 [installato]
clang-format/kinetic,kinetic,now 1:15.0-55.1ubuntu1 amd64 [installato]
clang-tidy-15/kinetic,now 1:15.0.2-1 amd64 [installato]
clang-tidy/kinetic,kinetic,now 1:15.0-55.1ubuntu1 amd64 [installato]
clang-tools-15/kinetic,now 1:15.0.2-1 amd64 [installato]
clang/kinetic,kinetic,now 1:15.0-55.1ubuntu1 amd64 [installato]
clangd-15/kinetic,now 1:15.0.2-1 amd64 [installato, automatico]
clangd/kinetic,kinetic,now 1:15.0-55.1ubuntu1 amd64 [installato]
libclang-common-15-dev/kinetic,now 1:15.0.2-1 amd64 [installato]
libclang-cpp14/jammy,jammy,now 1:14.0.6-3~22.04.sav0 amd64 [installato, automatico]
libclang-cpp15/kinetic,now 1:15.0.2-1 amd64 [installato, automatico]
libclang1-14/jammy,jammy,now 1:14.0.6-3~22.04.sav0 amd64 [installato, automatico]
libclang1-15/kinetic,now 1:15.0.2-1 amd64 [installato, automatico]

**Comment by lgritz** [comment]
Yeah, it was the libclang parts that I was looking for.

I'm not sure, definitely guessing here. But the next thing I would try is maybe seeing if it helps if you aren't mixing clang-14 and clang-15 components. Can you try removing all of the "14" libclang parts, and make sure you have the "15" versions of them installed? So, in other words, you can be sure that it finds all totally consistent libclang15 parts?

I'm honestly not sure this is the cause. You clearly have those components, so I'm not sure why it would have trouble finding that include file.

**Comment by lgritz** [comment]
The other think I would suggest is maybe when you run the `cmake --build` step, you perhaps try using the `-v` flag (verbose) to make it print the exact commands it is using to invoke the compiler, so we can see exactly which `-I` and `-isystem` options it uses to tell it where to find include files?

**Comment by dacorsa** [comment]
thanks i used 

cmake --build . --parallel 32 -v --resolve-package-references=on

and installed libclang-15-dev libclang-cpp15-dev NOW WORKS !
 Thanks for all
