### ISSUE TITLE
outputs to an unused node clobber other data

### ISSUE THREAD

**Issue by sfriedmapixar** [AcademySoftwareFoundation/OpenShadingLanguage#943]
The loop in BackendLLVM::build_llvm_instance that generates the llvm_assign_impl's to copy layer outputs to connected layer inputs doesn't check if the destination symbol is valid.  If an upstream node feeds multiple downstream nodes, and one of the downstream nodes is pruned, these assignments will overwrite something else -- in the case I saw, it overwrote the layer_run flags which caused rather unfathomable behavior.  

It looks like a simple guard like 
if(m_layer_remap[layer] != -1) {}
to prevent generating the assignments is sufficient to prevent problems.  Sorry I don't have a simple repro case handy.

Linux, LLVM 5.0.1, OSL 1.8.2+SIMD but looks like it's still there in master

**Comment by lgritz** [comment]
I'll check this out, thanks.

**Comment by sfriedmapixar** [comment]
Pinging this issue, in case it's related to one lgritz was mentioning running into.

**Comment by lgritz** [comment]
Hmmm, I don't recall what I figured out about this. 🤦

**Comment by lgritz** [comment]
Thanks for the tip, that's another angle to try.

**Comment by lgritz** [comment]
I think this has been fixed for some time now.

https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/blob/master/src/liboslexec/llvm_instance.cpp#L1052

Does that look like the spot, and the fix you had in mind, @sfriedmapixar ?

**Comment by sfriedmapixar** [comment]
Yup, that looks like the fix, so we can at least close this issue.

**Comment by lgritz** [comment]
I would gladly have embraced the embarrassment and shame of having let this slip and turn out it was responsible for my current issue, in exchange for it pointing to the quick fix to my actual problem. :-)
